name: Build GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Prepare Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Install requirements (mkdocs-material)
        run: pip install mkdocs-material
      - name: Build website
        run: mkdocs gh-deploy --force
  modify:
    name: Modify Generated Files
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout latest commit of gh-pages
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install requirements (js-beautify)
        run: npm install -g --location=global js-beautify --no-fund
      - name: Download JS Beautify config file
        run: wget -O jsbeautify.json https://raw.githubusercontent.com/EXMServer/EXM-KB/main/jsbeautify.json
      - name: Beautify files
        run: | 
          find . -type f -name '*.js' ! -name '*.min.js' -exec js-beautify -r '{}' --config jsbeautify.json \;
          find . -type f -name '*.css' ! -name '*.min.css' -exec css-beautify -r '{}' --config jsbeautify.json \;
          find . -type f -name '*.html' -exec html-beautify -r '{}' --config jsbeautify.json \;
      - name: Manually set CNAME
        run: |
          echo "kb.exm.haipa.xyz" > CNAME
          git add CNAME
      - name: Save changes to gh-pages branch
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply beautified files
          branch: gh-pages
          file_pattern: ./*.js ./*.html ./*.css
  publish:
    name: Publish GitHub Pages
    runs-on: ubuntu-latest
    needs: modify
    steps:
    - name: Checkout latest commit of gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
    - name: Deploy GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: .
        clean-exclude: |
          CNAME
