name: Build GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
      - name: Prepare Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Prepare Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install requirements
        run: |
          echo "Installing mkdocs-material"
          pip install mkdocs-material
          echo "Installing js-beautify"
          npm install -g --location=global js-beautify --no-fund
      - name: Build website
        run: mkdocs gh-deploy --force
      - name: Beautify files
        run: | 
          echo "Beautify files"
          js-beautify -r ./site/**/*.js
          css-beautify -r ./site/**/*.css
          html-beautify -r ./site/**/*.html
      - name: Save changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply beautified files
          branch: gh-pages
